src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Null_;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 * @Vich\Uploadable
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $technology;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $finish_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $image = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;
    /**
     * @var File|null $imageFile
     * @Vich\UploadableField(mapping="images_projets", fileNameProperty="image")
     */
    private ?File $imageFile = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $documentation;
    /**
     * @var File|null $docfile
     * @Vich\UploadableField(mapping="documentation_projets", fileNameProperty="documentation")
     */
    private ?File $docFile = null;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bilan;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTechnology(): ?string
    {
        return $this->technology;
    }

    public function setTechnology(string $technology): self
    {
        $this->technology = $technology;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getFinishAt(): ?\DateTimeInterface
    {
        return $this->finish_at;
    }

    public function setFinishAt(\DateTimeInterface $finish_at): self
    {
        $this->finish_at = $finish_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image = null): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
        if ($imageFile){
            $this->update_at = new \DateTime();
        }
    }

    /**
     * @return mixed
     */
    public function getDocumentation()
    {
        return $this->documentation;
    }

    /**
     * @param mixed $documentation
     */
    public function setDocumentation($documentation): void
    {
        $this->documentation = $documentation;
    }

    /**
     * @return File|null
     */
    public function getDocFile(): ?File
    {
        return $this->docFile;
    }

    /**
     * @param File|null $docFile
     */
    public function setDocFile(?File $docFile): void
    {
        $this->docFile = $docFile;
        if ($docFile){
            $this->update_at = new \DateTime();
        }
    }

    /**
     * @return mixed
     */
    public function getBilan()
    {
        return $this->bilan;
    }

    /**
     * @param mixed $bilan
     */
    public function setBilan($bilan): void
    {
        $this->bilan = $bilan;
    }
}

src/Entity/Timeline.php
<?php

namespace App\Entity;

use App\Repository\TimelineRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TimelineRepository::class)
 */
class Timeline
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $nameTechnology;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $finish_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameTechnology(): ?string
    {
        return $this->nameTechnology;
    }

    public function setNameTechnology(string $nameTechnology): self
    {
        $this->nameTechnology = $nameTechnology;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getFinishAt(): ?\DateTimeInterface
    {
        return $this->finish_at;
    }

    public function setFinishAt(\DateTimeInterface $finish_at): self
    {
        $this->finish_at = $finish_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

templates/component/competence.html.twig
<!--competences-->
<section class="page-section pt-3 pb-3" id="competence">
    <div class="container mt-5 mb-5">
        <div class="row text-dark">
            <div class="col-md-6 offset-md-3">
                <h2 class="page-section-heading text-secondary text-center">Compétences</h2>
                <ul class="timeline">
                    {% for timeline in timelines %}
                    <li>
                        <a class=" text-dark shadow" >{{ timeline.nameTechnology}}</a>
                        <a  class="float-right text-dark shadow">{{ timeline.createdAt | date('d/m/y')}}----{{ timeline.finishAt | date('d/m/y')}}</a>
                        <p>{{ timeline.description}}</p>
                    </li>
                    {%endfor%}
                </ul>
            </div>
        </div>
    </div>
</section>

<div class="pd-parallax" datasrc="{{ asset('statics/images/projet2.jpg') }}"></div>

templates/component/contact.html.twig
<!--Contact-->
<section class="page-section pt-3 pb-3" id="contact">
    <div class="container">
        <h2 class=" text-secondary text-center mb-4">Contactez-moi</h2>
        {{ form_start(form,{'attr': {
            'class': 'text-center border border-light shadow p-5',
        }} ) }}

        <div class="form-row mb-4">
            <div class="col">
                {{ form_widget(form.name,{
                    'attr': {
                        'class': 'form-control',
                        'placeholder': 'Nom'
                    }
                }) }}
            </div>
            <span class="erreur">
        {{ form_errors(form.name) }}
                            </span>
            <div class="col">
                {{ form_widget(form.lastname,{
                    'attr': {
                        'class': 'form-control',
                        'placeholder': 'Prénom',
                        'style':'margin-top:10px;'
                    }
                }) }}
            </div>
            <span class="erreur">
{{ form_errors(form.lastname) }}
                            </span>
        </div>
        <div class="col">
            {{ form_widget(form.email,{
                'attr': {
                    'class': 'form-control',
                    'placeholder': 'Email'
                }
            }) }}
        </div>
        <span class="erreur">
{{ form_errors(form.email) }}

                            </span>
        <div class="col">
            {{ form_widget(form.message,{
                'attr': {
                    'class': 'form-control',
                    'placeholder': 'Message',
                    'style':'margin-top:10px;'
                }
            }) }}
        </div>
        <span class="erreur">
{{ form_errors(form.message) }}

                            </span>
        <button class="btn btn-dark my-4 btn-block" type="submit">Envoyer</button>
        {{ form_end(form) }}
    </div>
</section>
<div class="pd-parallax" datasrc="{{ asset('statics/images/projet1.jpg') }}"></div>

templates/component/presentation.html.twig
<section class="page-section pt-3 pb-3" id="about">
    <div class="container ">
        <div class="content-parallax">
            <div class="text-center">
                <img  class="img-fluid img-thumbnail shadow img-presentation" src="{{ asset('statics/images/GONCALVES%20LAURA.jpg') }}">
                <h1 class="section-heading text-uppercase tittle-services"> Développeuse Web </h1>
                <p class="section-subheading text-muted">En cours de formation</p>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <i class=" fas fa-graduation-cap description-bloc-icon" ></i>
                    <p class="text-muted">  Baccalauréat scientifique  </p>
                </div>
                <div class="col-md-4">
                    <i class="fas fa-home description-bloc-icon"></i>
                    <p class="text-muted"> Vémars 95</p>
                    <p class="text-muted"> Dugny 93</p>
                </div>
                <div class="col-md-4">
                    <i class="fas fa-car description-bloc-icon "></i>
                    <p class="text-muted"> Permis B</p>
                </div>
            </div>
            <a href="{{ asset('statics/cv/CVLauraGonçalves.pdf') }}" target="_blank"> <button type="button" class=" rounded mx-auto d-block btn btn-light shadow">Télécharger mon CV</button> </a>
        </div>
    </div>
</section>
<div class="pd-parallax" datasrc="{{ asset('statics/images/projet1.jpg') }}"></div>

templates/component/réalisation.html.twig
<!--Portfolio-->
<section class="page-section pt-3 pb-3 portfolio" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="page-section-heading text-secondary text-center">Projets</h2>
        </div>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                {% for projet in projets %}
                <div class="swiper-slide">
                    <div  class="card" style="18em;">
                        <img class="card-img-top" src="{{ asset('statics/images/projets/' ~ projet.image)  }}">
                        <div class="card-body">
                            <h5 class="card-title"></h5>
                            <p class="card-text"></p>
                            <a href="{{
                            path('single_projet',
                                {'id': projet.id})
                            }}" target="_blank" class="btn btn-dark">Voir le Projet</a>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>
            <div class="swiper-button-prev" style="color: #212529"></div>
            <div class="swiper-button-next" style="color: #212529"></div>
        </div>
    </div>
</section>

<div class="pd-parallax" datasrc="{{ asset('statics/images/projet3.jpg') }}"></div>

templates/component/single_projet.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <body>
    <div class="container-fluid">
        <h1 class="display-4">{{ projet.title }}</h1>
        <p class="lead"></p>
        {% if projet.documentation  %}
            <a href="{{ asset('statics/documentations/' ~  projet.documentation ) }}"  download> <button type="button" class=" rounded  btn btn-light shadow" >Télécharger la documentation</button> </a>
        {% endif %}
        <p class="lead"></p>
        <hr class="my-4">
        <p> Description : {{ projet.description}}</p>
        <p> Stack Technique: {{ projet.technology}} </p>
        <p> Période de réalisation: {{ projet.createAt | date('d/m/y')}}</p>
    </div>
    <hr class="hr">
    <div class="blocImagePhoto mt-5 mb-5">
        <div>
            <p> Bilan </p>
            <span>{{ projet.bilan | raw }}</span>
        </div>
        <img class="card-img-top" src="{{ asset('statics/images/projets/' ~ projet.image)  }}">
    </div>
    </section>
    <section class="bg-dark shadow pt-3 pb-3">
        <footer class="text-center">
            <a class="btn btn-light btn-lg mt-2 mb-4" href="index.php" role="button">retour à l'accueil</a>
            <h5 class=" text-light">© Design by Laura Goncalves </h5>
            <a href="tel:06.20.78.79.72" class="mx-2" role="button"><i class="fa fa-phone text-light "></i></a>
            <a href="mailto:laura.goncalves@lyceestvincent.fr" class="mx-2" role="button"><i class="fa fa-envelope text-light"></i></a>
            <a href="https://www.linkedin.com/feed/" class="mx-2" role="button"><i class="fab fa-linkedin-in text-light "></i></a>
            <a href="https://github.com/lauraagss" class="mx-2" role="button"><i class="fab fa-github text-light"></i></a>

        </footer>
    </section>
    </body>
{% endblock %}